# Autor: Christian Langner
spring.application.name=AsyntraCore
spring.profiles.active=home

# Database - injected via Env-Vars
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Vector Search (pgvector)
spring.jpa.properties.hibernate.postgresql.vector_type=true