# H2 Datenbank Einstellungen (läuft ohne Admin-Rechte)
spring.datasource.url=jdbc:h2:mem:syntracoredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Damit wir die Datenbank im Browser anschauen können
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update