spring.datasource.url=jdbc:postgresql://localhost:5432/ayntracore
spring.datasource.username=ayntra
spring.datasource.password=ayntra
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=50000
spring.jpa.show-sql=true

# Logging Levels
logging.level.com.ayntracore=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# OpenAI API Key
openai.api.key=${OPENAI_API_KEY}
civitai.api.key=${CIVITAI_API_KEY}

# Adapter Configuration
adapter.image.provider=openrouter